// Synthetic infrastructure fixture, NOT a fresh business or visual benchmark.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {skillRoot,mintTemplatePath} from '../scripts/lib/config.mjs';
import {readJson,writeJson} from '../scripts/lib/creative-contract.mjs';
import {inspectNative} from '../scripts/inspect-ppt.mjs';
import {inspectPptxPackage} from '../scripts/lib/pptx-metadata.mjs';
import {nativeObjects,auditNativeContent} from '../scripts/lib/native-audit.mjs';
import {checkRun} from '../scripts/lib/creative-contract.mjs';

const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'creative-native-')),run=path.join(tmp,'run');
const cli=(script,args)=>execFileSync(process.execPath,[path.join(skillRoot,'scripts',script),...args],{encoding:'utf8',env:process.env,maxBuffer:8e6});
fs.writeFileSync(path.join(tmp,'source.txt'),'试点团队预计全年投入120万元，仅用于A项目。\n项目 金额 A 120 B 80\nJan Feb Mar 投入 10 20 30');
fs.writeFileSync(path.join(tmp,'prompt.txt'),'合成原生对象基础测试，一页，保留全部数据。');
writeJson(path.join(tmp,'inputs.json'),[{path:path.join(tmp,'source.txt'),sourceOrigin:'raw-source'}]);
cli('prepare.mjs',[path.join(tmp,'inputs.json'),path.join(tmp,'prompt.txt'),run]);
const source=readJson(path.join(run,'source-model.json')),ids=source.sourceUnits.map(u=>u.id);
source.sourceUnits[2].requiredComponents=['Jan','Feb','Mar','投入','10','20','30'];
source.sourceUnits[2].componentReview={status:'reviewed',sourceText:source.sourceUnits[2].text};
writeJson(path.join(run,'source-model.json'),source);
const require=createRequire(path.join(process.env.RUNTIME_NODE_MODULES,'package.json'));
const {FileBlob,PresentationFile}=await import(pathToFileURL(require.resolve('@oai/artifact-tool')).href);
const {applyPresentationChartFont}=await import(pathToFileURL(path.join(process.env.PRESENTATIONS_SKILL_DIR,'container_tools/artifact_tool_utils.mjs')).href);
const family='Arial';
writeJson(path.join(run,'brief.json'),{audience:'开发验收',goal:'检查基础适配器',fonts:[family],template:{id:'mint-template-16x9/1',mode:'native-brand-shell'},explicitSlideCount:1,stories:[{id:'s',sourceRefs:ids,message:'原生对象保留数据',firstFocus:'投入与条件',composition:'左侧自然短表，右侧原生数据图',emphasis:'条件与数值可读',displayCopy:{title:'原生对象验收',body:source.sourceUnits[0].text}}],requirements:[]});
cli('preflight.mjs',[run]);
fs.copyFileSync(new URL(import.meta.url),path.join(run,'build.mjs'));
const p=await PresentationFile.importPptx(await FileBlob.load(mintTemplatePath)),s=p.slides.items[0];s.background.fill='#FBFCF8';
const t=s.shapes.add({geometry:'textbox',position:{left:48,top:48,width:1184,height:56},fill:'none',line:{fill:'none',width:0}});
t.name='Mint content title';t.text=source.sourceUnits[0].text;t.text.style={typeface:'思源黑体 CN Regular',fontSize:32*96/72,bold:true,color:'#12695D',autoFit:'none',insets:{left:0,right:0,top:0,bottom:0}};
const table=s.tables.add({rows:3,columns:2,left:60,top:185,width:360,height:180,columnWidths:[200,160],values:[['项目','金额'],['A',120],['B',80]]});table.name='costs';
for(let r=0;r<3;r++) for(let c=0;c<2;c++){const cell=table.getCell(r,c);cell.text.style={typeface:family,fontSize:24,color:'#10362E',autoFit:'none'};cell.fill=r===0?'#DDEFE8':'#FFFFFF';}
const font={typeface:family,fontSize:24};
const chart=s.charts.add('bar',{title:'投入',titlePlacement:'aboveChart',position:{left:480,top:160,width:730,height:450},categories:['Jan','Feb','Mar'],series:[{name:'投入',values:[10,20,30],fill:'#078C87'}],barOptions:{direction:'column',grouping:'clustered'},hasLegend:true,legend:{textStyle:font},xAxis:{textStyle:font},yAxis:{textStyle:font},dataLabels:{showValue:true,position:'outEnd',textStyle:font},titleTextStyle:font});chart.name='trend';applyPresentationChartFont(chart,{fontFamily:family});
const candidate=path.join(run,'candidate.pptx');await (await PresentationFile.exportPptx(p)).save(candidate);
const inspection=await inspectNative(candidate,path.join(run,'inspection'));
const pkg=await inspectPptxPackage(candidate),objects=nativeObjects(pkg.slideXml[0]);
const name=predicate=>objects.find(predicate)?.name;
const map={workbookSnapshot:'new-literal-data',slides:[{id:'slide-1',storyId:'s',carriers:[{id:'copy',type:'text',objectNames:[name(o=>o.text===source.sourceUnits[0].text)],sourceUnitIds:[ids[0]]},{id:'table',type:'table',objectNames:[name(o=>/<a:tbl\b/.test(o.xml))],sourceUnitIds:[ids[1]],data:{headers:['项目','金额'],rows:[['A',120],['B',80]]}},{id:'chart',type:'chart',objectNames:[name(o=>/<c:chart\b/.test(o.xml))],sourceUnitIds:[ids[2]],variant:'column',data:{categories:['Jan','Feb','Mar'],series:[{name:'投入',values:[10,20,30]}]}}]}],capacityAttempts:[]};
writeJson(path.join(run,'evidence-map.json'),map);
const context=await checkRun(run,{requirePreflight:true}),audit=await auditNativeContent(candidate,inspection,map,context);writeJson(path.join(run,'adapter-test.json'),audit);
assert.equal(audit.passed,true,JSON.stringify(audit.issues));
const wrong=structuredClone(map);wrong.slides[0].carriers[2].data.series[0].values[1]=999;
assert.equal((await auditNativeContent(candidate,inspection,wrong,context)).passed,false);
const missing=structuredClone(map);missing.slides[0].carriers.shift();assert.equal((await auditNativeContent(candidate,inspection,missing,context)).passed,false);
const final=path.join(run,'output','native-smoke.pptx');
console.log(cli('finalize-creative-ppt.mjs',[run,candidate,final,path.join(run,'inspection','inspection.json')]));
const result=readJson(final+'.creative-audit.json');assert.equal(result.passed,true);assert.equal(result.status,'technical-candidate-awaiting-independent-review');
console.log(JSON.stringify({status:'native-fixture-pass',run,final,renderedImage:inspection.slides[0].renderedImage,notBusinessBenchmark:true}));
