import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {templateOutputIssues,templatePackage} from '../scripts/lib/template-contract.mjs';
const template=path.resolve('assets/mint-ppt-16x9-template.pptx');
const require=createRequire(path.join(process.env.RUNTIME_NODE_MODULES,'package.json'));
const {FileBlob,PresentationFile}=await import(pathToFileURL(require.resolve('@oai/artifact-tool')).href);
const presentation=await PresentationFile.importPptx(await FileBlob.load(template));
assert.equal(presentation.slides.items.length,1);
presentation.slides.items[0].duplicate();presentation.slides.items[0].duplicate();
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'mint-template-test-')),out=path.join(tmp,'duplicated.pptx');
await (await PresentationFile.exportPptx(presentation)).save(out);
const pkg=await templatePackage(out);assert.equal(pkg.slides.length,3);
const result=await templateOutputIssues(out,{templateFile:template,requireAutomaticPageNumbers:true});
assert.equal(result.passed,true,JSON.stringify(result.issues));
console.log(JSON.stringify({status:'template-pass',slides:pkg.slides.length,automaticPageFields:pkg.slides.map(s=>s.automaticFields)}));
